services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=proyect
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nodejs:
    image: my-node-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - logs:/usr/src/app/logs
      - profile_photos:/usr/src/app/public/profilePhotos

volumes:
  pgdata:
  logs:
  profile_photos:
